# Generated by Django 4.1.4 on 2022-12-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cuisine',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='fiyat',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='mutfak',
        ),
    ]
