# Generated by Django 4.1.4 on 2022-12-27 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_rename_cuisine_menu_ad_rename_price_menu_fiyat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='kategori_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='menuapp.menucategory'),
        ),
    ]
